### ISSUE TITLE
The preview feature "mongoDb" is not known

### ISSUE THREAD

**Issue by ledesmablt** [pantharshit00/coc-prisma#16]
Prisma is starting to support [mongoDb](https://www.prisma.io/docs/concepts/database-connectors/mongodb). But latest version at the time of writing (v0.9.0) is throwing an error when i add `mongoDb` to `previewFeatures`

![image](https://user-images.githubusercontent.com/22242264/128659322-344af5a9-fed4-467e-b897-360b5387ad2d.png)

**Comment by pantharshit00** [comment]
I just updated the SDK. This should be fixed in 0.10.0

I have personally moved to nvim lsp now so please let me know if something doesn't work.

**Comment by ledesmablt** [comment]
tested and working for me, many thanks!
