### ISSUE TITLE
Does not seem to work longer

### ISSUE THREAD

**Issue by albingroen** [pantharshit00/coc-prisma#18]
I have this specified in my init.vim file.

```
let g:coc_global_extensions = ['coc-eslint', 'coc-json', 'coc-pairs', 'coc-prettier', 'coc-tailwindcss', 'coc-tsserver', 'coc-emmet', 'coc-prisma']
```

But, I don't seem to get any validation or autocompletion?
![image](https://user-images.githubusercontent.com/19674362/129950142-0ec33d10-4326-431a-b95a-0e1275e3d458.png)

---

Neovim version: v0.5.0
coc-prisma version: v0.10.0

**Comment by pantharshit00** [comment]
Can you please share output of `:CocCommand workspace.showOutput`?


Try reinstalling it once as well

**Comment by albingroen** [comment]
This is what I see when I run the command

<img width="885" alt="image" src="https://user-images.githubusercontent.com/19674362/130408639-69f67fa9-72c0-4165-99a5-7da24f78d77a.png">

I have tried re-installing the plugin several times.

**Comment by pantharshit00** [comment]
Try adding `"prisma.prismaFmtBinPath": ""` in `coc-settings.json

**Comment by albingroen** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/19674362/130412464-1dd28498-12dc-45da-872c-a64c27cfc62f.png">

**Comment by pantharshit00** [comment]
That looks alright. Can I see your vim config? Also, please put that option if not already done. There is a null check issue in the main extension so that property might be required

**Comment by albingroen** [comment]
Alright, here's my vim (neovim) configuration: https://github.com/albingroen/dotfiles/tree/master/vim

**Comment by pantharshit00** [comment]
0.11 changed how this extension works and eliminates use of binary which was the major cause of issues. 

Please try 0.11 release
